version: '3'

services:

  pyapp:
    container_name: golang
    build: 
      context: ../app
      dockerfile: dockerfile
    image: golang:latest
    ports:
      - 8000:8000
    restart: always
    networks:
      gonet:
        ipv4_address: 172.10.10.2

networks:
  gonet:
    driver: bridge
    ipam:
      config:
        - subnet: 172.10.10.0/16
